/**
 * VPS Services Bundler
 *
 * Uses esbuild to bundle VPS services into self-contained scripts
 * that can be deployed to servers during provisioning.
 *
 * Each service is bundled independently with its dependencies inlined.
 *
 * Usage:
 *   npx tsx apps/api/src/vps/bundle.ts
 *
 * Output:
 *   apps/api/src/vps/dist/
 *   ├── shared.bundle.js       (shared utilities)
 *   ├── sovereign-shield.bundle.js
 *   ├── file-api.bundle.js
 *   ├── agent-bridge.bundle.js
 *   └── enforcer.bundle.js
 */

import * as esbuild from "esbuild";
import * as path from "path";
import * as fs from "fs";

const VPS_DIR = path.dirname(new URL(import.meta.url).pathname);
const SERVICES_DIR = path.join(VPS_DIR, "services");
const DIST_DIR = path.join(VPS_DIR, "dist");

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
}

interface BundleConfig {
  name: string;
  entryPoint: string;
  platform: "node" | "browser";
  external?: string[];
}

const BUNDLES: BundleConfig[] = [
  // Shared utilities bundle (imported by other services)
  {
    name: "shared",
    entryPoint: path.join(SERVICES_DIR, "shared/index.ts"),
    platform: "node",
  },
  // TODO: Add service bundles as they are modularized
  // {
  //   name: "sovereign-shield",
  //   entryPoint: path.join(SERVICES_DIR, "sovereign-shield/src/main.ts"),
  //   platform: "node",
  //   external: ["better-sqlite3"], // Native module - must be installed on VPS
  // },
];

async function bundleService(config: BundleConfig): Promise<void> {
  const outfile = path.join(DIST_DIR, `${config.name}.bundle.js`);

  console.log(`Bundling ${config.name}...`);

  try {
    await esbuild.build({
      entryPoints: [config.entryPoint],
      bundle: true,
      platform: config.platform,
      target: "node18",
      format: "cjs", // CommonJS for Node.js compatibility
      outfile,
      external: config.external || [],
      minify: false, // Keep readable for debugging
      sourcemap: false,
      banner: {
        js: `/**
 * ${config.name} - Bundled VPS Service
 * Generated: ${new Date().toISOString()}
 * DO NOT EDIT - This file is auto-generated by bundle.ts
 */
`,
      },
    });

    const stats = fs.statSync(outfile);
    console.log(`  ✓ ${config.name}.bundle.js (${(stats.size / 1024).toFixed(1)} KB)`);
  } catch (error) {
    console.error(`  ✗ Failed to bundle ${config.name}:`, error);
    throw error;
  }
}

async function main(): Promise<void> {
  console.log("VPS Services Bundler");
  console.log("====================\n");

  const startTime = Date.now();

  for (const config of BUNDLES) {
    await bundleService(config);
  }

  const elapsed = Date.now() - startTime;
  console.log(`\nBundled ${BUNDLES.length} services in ${elapsed}ms`);
}

main().catch((error) => {
  console.error("Bundle failed:", error);
  process.exit(1);
});
